# ???
server:
  port: 8888

# zookeeper??
apache:
  zookeeper:
    # ?????????????????????ip1:host,ip2:host
    connect-url: 192.168.150.103:2181,192.168.150.103:2182,192.168.150.103:2183
    # ?????????ms
    session-timeout: 10000
    # ?????????ms
    connection-timeout: 40000
    # ACL?????????
    # scheme: auth
    # ????id
    # auth_id: admin:123456
  # ????
  retry-policy:
    # ???????
    base-sleep-time: 1000
    # ??????
    max-retries: 5
    # ????????
    max-sleep: 30000


